### ISSUE TITLE
Further readings on feedback

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#12]
Good resources on feedback include:
- [Thanks for the Feedback](https://www.amazon.com/Thanks-Feedback-Science-Receiving-Well/dp/0143127136/ref=sr_1_1?ie=UTF8&qid=1496938375&sr=8-1&keywords=feedback)
- [Gormally article](http://www.lifescied.org/content/13/2/187.short)
- [Tell  me what I did wrong](https://academic.oup.com/jcr/article/39/1/22/1823160/Tell-Me-What-I-Did-Wrong-Experts-Seek-and-Respond)
- [Feedback as a resource](http://www.sciencedirect.com/science/article/pii/0030507383901563)
- [Performance Feedback and Teacher's use of Praise](https://muse.jhu.edu/article/492683/summary)

**Comment by raynamharris** [comment]
The comics are great but I do think that many people will be interested in reading more about how to give/receive feedback.

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
