### ISSUE TITLE
Bug BBQ, reorganisation, release

### ISSUE THREAD

**Issue by lexnederbragt** [ErinBecker/instructor-training-reorg#123]
Having not been able to attend the Issue Bonanza, this is based on my impressions of the process and I may be misinformed. I thought that with an issue bonanza done and a Bug BBQ for the release planned a week from now, the reorganisation process would have come further along. I submitted a bug fix which was put on hold because episode renumbering has not been done. There is a looooong list of sometimes pretty large issue in #45. Addressing these may well take more than two days, and these surely will lead to new bugs (typos etc), and discussions amongst us. I also see many proposed changes *adding* material/exercises, and few removing anything, which mean we could end up with a much longer workshop than it already is.

All of this is great stuff, and I support the reorganisation. However, I feel we rather shouldn't rush this through, and thus my concern is that a release on August 10 is a bit too optimistic...

What say y'all?

**Comment by karenword** [comment]
I'm just joining in here and also feeling a bit overwhelmed. I participated in the issue bonanza, but mostly as a spectator -- I spent much of that time reading existing comments and changes. I imagine those who have been more closely involved have a better sense of direction and growth boundaries (?) for this re-development. This definitely echoes my perspective, though.  I would love to have more time to help polish this nicely. (And I actually have time now!)

**Comment by ChristinaLK** [comment]
Thanks @lexnederbragt and @karenword .  I think @ErinBecker will decide and let everyone know.  :)

**Comment by ErinBecker** [comment]
Thanks @lexnederbragt, @karenword and @ChristinaLK. I had hoped to be further along in the development process at this point, but there's still quite a bit to do, so I think it's likely we'll need to delay the release a bit. I've been teaching the past two days, but will have a chance to look through the status of the repo shortly. At that point, I'll have a clearer picture of what a reasonable release date might be and will update the issue with some thoughts.

**Comment by ErinBecker** [comment]
That having been said, I was really happy to see all the amazing activity during the Bug BBQ! We've made great progress, even if we're not done yet. ;-)

**Comment by lexnederbragt** [comment]
Thanks, Erin. And I agree, much work has been done!
