### ISSUE TITLE
Add reference for Mental Models (02-mindset)

### ISSUE THREAD

**Issue by lexnederbragt** [ErinBecker/instructor-training-reorg#128]
In the "How Learning Works: The Importance of Practice"
episode, one or more references are requested here:

>In many cases, this prior knowledge is incomplete or inaccurate. Inaccurate beliefs can be termed "misconceptions" and
can impeded learning by making it more difficult for learners to incorporate new, correct information into their mental
models.

And

> Broadly speaking, misconceptions fall into three categories:
> 
> *   Simple *factual errors*, such as believing that Vancouver is the capital of British Columbia.
>     These are the easiest to correct.
> *   *Broken models*, such as believing that motion and acceleration must be in the same direction.
>     We can address these by having them reason through examples to see contradictions.
> *   *Fundamental beliefs*,
>     such as "the world is only a few thousand years old"
>     or "human beings cannot be affecting the planet's climate".
>     These beliefs are deeply connected to the learner's social identity
>     and are the hardest to change.

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
