### ISSUE TITLE
Add internal link to Mindset (09-mindset)

### ISSUE THREAD

**Issue by lexnederbragt** [ErinBecker/instructor-training-reorg#129]
In the "Creating a Positive Learning Environment: Mindset"
episode, an internal reference is requested:

> This tendency prevents fixed-mindset people from getting opportunities to practice
> and receive feedback, which as we've discussed (FIXME add link to practice module) is essential to learning.

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
