### ISSUE TITLE
incorporate checkout

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#13]
Currently checkout is an "extra", move into the afternoon wrap up for day 2.

**Comment by raynamharris** [comment]
Can we rename the "morning wrap-up" and "afternoon wrap-up" sections?  If this course is every split into four half days or taken by someone in a different zone, then the names could be misleading. 

More importantly, I think the name could be made much more informative. For instance, all the "wrap-up" episodes are designed to collect feedback from the leaners, so maybe these could be renamed  "Workshop Feedback 1,2,3, and 4". Or, maybe this could be condensed into a single "Workshop feedback episode" and the instructor notes explain how/when it should be administered. 

Additionally, the 1st afternoon wrap explains the homework (2 reading assignments and prep for live coding), and the 2nd afternoon wrap up explains the 3 steps to checkout. Can these be renamed "homework/" and "next steps to certification".

**Comment by ErinBecker** [comment]
This is now in the wrap up for day 2.
