### ISSUE TITLE
better way to introduce reverse instructional design?

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#154]
I'm wondering if there is a better way to introduce the reverse instructional design material in the [learning objectives lesson](https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_episodes/14-learning-objectives.md).

Currently it starts with "Most people design courses as follows: ...".

I worry that this word use may offend some people at worst and not be relatable at best, especially since we are reaching 1) people with formal teaching education and 2) people without faculty positions who do not report to chairs of departments.

Can we keep the heart of the discussion (forward design: developing lecture slides, then quizzes, then final exam) but change the tone?

**Comment by ChristinaLK** [comment]
One transition I've used in the past is "we've been talking a lot about learners, and you may have noticed a pattern of working backwards (doing MCQs, breaking ideas apart using concept maps) -- another way to do this is in how we design lessons -- back to front."

**Comment by naupaka** [comment]
I taught this last time in the framework of TDD. Learner profiles are the same as user stories, learning outcomes are the unit tests you do before you start coding, and them once you set all of that up, you figure out how to write the code/curriculum needed to pass the 'tests'.

**Comment by raynamharris** [comment]
Thanks @naupaka and @ChristinaLK. I know that both of the language y'all are using to introduce the concept is already present in the episode text. 

So, if its okay with everyone, Ill create a pull request to remove the "Chair of your department says" framework.

**Comment by ChristinaLK** [comment]
sounds good!

**Comment by ErinBecker** [comment]
@raynamharris - I have a pending pull request suggesting removing the learning objectives episode and replacing with an episode on developing good exercises and getting feedback on exercise design. Would appreciate your thoughts about this switch. #180

**Comment by ErinBecker** [comment]
Closing based on #180
