### ISSUE TITLE
move question about mental models (02-practice)

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#159]
Move question about mental models to 02-practice after the discussion of MCQs.

- Add mental model questions cut from previous episode?
*Which of these questions assesses flaws in a student's mental model of a domain? You don't need to provide answers for these questions.*		
1. I'm not sure what a mental model is.		
2. "In Python, what is the expected output for the following statement: 1 + '2'"		
 	(a) '12'		
 	(b) TypeError		
 	(c) '3'		
 	(d) 3		
 3. "Rate your experience with the R programming language."		
 	(a) never used it		
 	(b) beginner		
 	(c) intermediate		
 	(d) expert		
 4. "What does the Unix command 'cut' do?"		
 	(a) Extracts sections from each line of input.		
 	(b) Sorts fields of a line		
 	(c) Searches the input file for lines containing a match to a pattern		
 	(d) Removes a given input from a line

**Comment by karenword** [comment]
Added to checklist - closing for cleanup

**Comment by ErinBecker** [comment]
Actually, I rather like this where it is, now that I look at it again. Closing my issue.
