### ISSUE TITLE
move "a corollary regarding novices" (02-practice)

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#165]
The text below was in the motivation episode, but it doesn't seem to belong there. Where would be a better place for it?

> ## A Corollary Regarding Novices
>
> Students are commonly _far_ too satisfied to not understand key points
> and remain confused.  If students remain confused, they are far less likely
> to adopt our "good enough" practices at the conclusion of the workshop.
> Encourage helpers to support confused students as far as possible within
> the flow of the workshop.
{: .callout}

**Comment by ChristinaLK** [comment]
Formative assessment?

**Comment by ErinBecker** [comment]
That's a great idea @ChristinaLK. I'll work on incorporating it there after some of the existing PRs are dealt with.

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
