### ISSUE TITLE
Add reference to more information about faded examples (05-memory)

### ISSUE THREAD

**Issue by lexnederbragt** [ErinBecker/instructor-training-reorg#168]
I would really like to know more about how to make good faded examples (as I suspect they are a very useful learning tool). If someone has a good *practical* reference/website/source, I'll add it to the appropriate episode.

**Comment by ErinBecker** [comment]
Thanks @lexnederbragt, I agree that this would be really useful. I suggest adding this to the new "Lesson Study" module (https://github.com/ErinBecker/instructor-training-reorg/pull/180). Added this to the checklist and closing here.
