### ISSUE TITLE
add MCQ to address motivation or prior knowlege

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#177]
1 of the 3 multiple choice questions (MCQ) in the [welcome episode](https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_episodes/01-welcome.md) will be moved to a later episode (see issue https://github.com/ErinBecker/instructor-training-reorg/issues/159).

I propose we add a question to assess trainee background or motivation. Some ideas could be:
- Which continents have you lived on?
- Which disciplines do you identify with?
- Which of the following motivate you to teach?

Any suggestions @kariljordan

**Comment by karenword** [comment]
Added to checklist - closing for cleanup

**Comment by ErinBecker** [comment]
@raynamharris

**Comment by ErinBecker** [comment]
Closing based on comment above.
