### ISSUE TITLE
Provide feedback to trainee exercises

### ISSUE THREAD

**Issue by lexnederbragt** [ErinBecker/instructor-training-reorg#24]
Discussion:

At the [DIBSI TTT](http://ivory.idyll.org/dibsi/instructor-training.html) we got feedback from trainees that they would like to get feedback from the trainers on their written exercises, e.g. formative assessment MCQs, faded examples, learning objectives. We did do that afterwards, adding comments in the etherpad. It turns out to be quite a bit of work - and thus would be a task for the second instructor, to be done while the first instructor is teaching the next module.

I think it would be a big benefit to give feedback rather than to have trainees write exercises and never hear anything about them. But, as said, it is time consuming.

**Comment by ErinBecker** [comment]
Related: https://github.com/ErinBecker/instructor-training-reorg/pull/180

@lexnederbragt would be interested in your thoughts.

**Comment by ErinBecker** [comment]
We can also add a note to Trainers to provide feedback on trainee exercises while trainees are working on other group discussions/exercises. There are several points in the two day workshop where Trainers have down time of 15 minutes to half an hour. The co-Trainer can also be working on feedback while the other Trainer is teaching. 

Making a note to add this to Trainer documentation (in the checklist) and closing here.
