### ISSUE TITLE
Revamp the workshop goals

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#25]
I would like to revisit the goals of the workshop that are listed on [the homepage](https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/index.md) 

I have three suggestions:
1. Keep the two existing goals but write them a little more concisely. 
2. Maybe articulate some other goals that we have for the program?
3. Maybe add a short list of "beyond the scope of this workshop" to help with participant expectations.

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
