### ISSUE TITLE
The Carpentries: duplication of Operations Guide material

### ISSUE THREAD

**Issue by jcoliver** [ErinBecker/instructor-training-reorg#26]
The Carpentries lesson (episode 22) has two points where learners are supposed to interact with the operations guide, but this could probably be condensed into one section. The first is at the start of the lesson under "Preparation and Discussion" and the second, more in-depth section is "Workshop Operations". The latter includes an exercise as well. I wonder if the first (Preparation and Discussion) could be dropped entirely - it seems a bit of a distraction before diving into the history of the Carpentries...

**Comment by raynamharris** [comment]
I agree we should strive to minimize redundancy.

**Comment by ErinBecker** [comment]
Closing based on #133
