### ISSUE TITLE
alternative learning objective challenge

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#27]
Twice, I received feedback from learners that they did not like the "Evaluate SWC and DC Learning Objectives" challenge, mostly because it was hard to improve something that was already good.  See https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_episodes/14-learning-objectives.md

So, this last time I modified the exercise to have them all evaluate a handful of learning objectives and identify the blooms level together.

**In the chat window, state the corresponding level of blooms taxonomy**
- Learners will be able to name three benefits of using a version control system like git.  
- Learners will be able to explain the difference between a database and a database manager.  
- Learners will be able to write conditional statements using if and elif. 
- Learners will be able to compare the collaboration features of git and dropbox. 

This modified exercise was much faster and interactive than the existing exercise. I think it was effective. 

What do y'all think about including this version of the challenge?

**Comment by raynamharris** [comment]
Oh, I also created a second learning objective exercise, which was also very fast and interactive. 

**Write your own learning objective (LO)**
- Write one LO for the lesson you live coded this morning
- Identify the bloom's level of taxonomy that this address
- Paste your LO and the corresponding bloom's level in the etherpad

This was also a very fast exercise that they completed in 3 minutes. 

I don't have the data to prove it, but I think this exercise had the most value because it related directly to a topic that these instructors-in-training will teach in the very near future. 

Thoughts?

**Comment by ErinBecker** [comment]
Closed with #104
