### ISSUE TITLE
Learning objectives episode lacks a visual aid

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#28]
IMO, the [learning objective episode](http://swcarpentry.github.io/instructor-training/19-lessons/) really needs a visual aid of the level's of blooms taxonomy OR a simplified table. 

I've taught this episode 3 times, and I've either display a simplified table or a visual aid. I think the visual is the best, mostly because a hyperlink to an image can be easily pasted in the etherpad for online workshops, whereas the tables are created inline and cannot be easily shown to learners in online workshops. 

My two favorite visuals are [this one](https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/) and [this one](https://carleton.ca/viceprovost/assessment-of-learning/learning-outcomes/blooms-taxonomy/). 

Is anyone else in favor of adding a visual aid?

**Comment by lexnederbragt** [comment]
I am in favor, and @smcclatchy had some great ones at the DIBSI TTT last week...
