### ISSUE TITLE
re-order lessons and learning objectives episode

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#29]
The current order of the [lessons and learning objectives episode](http://swcarpentry.github.io/instructor-training/19-lessons/) is:
1. learner profiles
2. learning objectives
3. reverse instructional design

When I taught with @smcclatchy, she flipped the script and taught:
1. reverse instructional design (but called it learner-centered design)
2. learner profiles
3. learning objectives

I copied Sue's approach at my recent workshop, and I think it worked really well. I like explicitly stating the reverse- or learner-center approach first because it nicely frames the rest of the episode. And then, you can say something like "the next step is designing assessment, which we covered yesterday with MCQs & faded/parsons examples, and the next step if organizing all the concepts into lessons, which we talked about yesterday when we discusses concept maps and short-term memory".

Then, this flows very nicely into talking more in-depth about what is covered in SWC/DC workshops and why.

**Comment by raynamharris** [comment]
This seems like a task that should be done later in the process so as not to cause merge conflicts if anyone else makes changes to the content on this page.

**Comment by ErinBecker** [comment]
I have a pending pull request suggesting removing the learning objectives episode and replacing with an episode on developing good exercises and getting feedback on exercise design. Would appreciate your thoughts about this switch. https://github.com/ErinBecker/instructor-training-reorg/pull/180

**Comment by ErinBecker** [comment]
Closing based on https://github.com/ErinBecker/instructor-training-reorg/pull/180
