### ISSUE TITLE
new instructor-trainer testimonials are missing

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#31]
We have so many new instructor-trainers!  It would be great if everyone could submit a PR with their motivation to teach here: https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_extras/testimonials.md

- [ ] Erin Becker (United States)
- [ ] Martin Callaghan (United Kingdom)
- [ ] Karen Cranston (United States)
- [x] Steve Crouch (United Kingdom)
- [x] Neal Davis (United States)
- [ ] Jonah Duckles (New Zealand)
- [ ] Chris Hamm (United States)
- [x] Rayna Harris (United States)
- [ ] Kari Jordan (United States)
- [x] Christina Koch (United States)
- [ ] Mateusz Kuzak (Netherlands)
- [ ] Karin Lagesen (Norway)
- [ ] Mark Laufersweiler (United States)
- [ ] Sue McClatchy (United States)
- [x] Lex Nederbragt (Norway)
- [x] Aleksandra Nenadic (United Kingdom)
- [ ] Jeff Oliver (United States)
- [ ] Aleksandra Pawlik (New Zealand)
- [ ] Ariel Rokem (United States)
- [ ] Maneesha Sane (United States)
- [ ] Tracy Teal (United States)
- [x] Fiona Tweedie (Australia)
- [x] Anelda van der Walt (South Africa)
- [ ] Allegra Via (Italy)
- [x] Alistair Walsh (Australia)
- [x] Belinda Weaver (Australia)
- [x] Jason Williams (United States)
- [x] Greg Wilson (Canada)
- [ ] Karen Word (United States)
- [ ] Naupaka Zimmerman (United States)

**Comment by ErinBecker** [comment]
Thanks Rayna! I'd actually love to migrate the Trainer testimonials to the Carpentry website (when we have one, which should be soon).

**Comment by raynamharris** [comment]
I agree the website is more appropriate. In that case, I can submit a PR to delete this file (and the reference to it in one of the lessons).

**Comment by raynamharris** [comment]
Closing this issue
