### ISSUE TITLE
Move stuff from reference to episodes

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#35]
There's a lot of good material in reference.md. Much of this could be moved to the appropriate episodes and highlighted there. I don't know if anyone ever looks at the references and I'd like to avoid burying this material there. 

Much of the material in reference.md is also quite wordy. Simplify and make more puchy!

**Comment by raynamharris** [comment]
I have never looked at the reference file. I'm in favor of moving the relevant content to a different file OR of moving this reference file to the _extras directory with the other instructor notes.
