### ISSUE TITLE
"Terms" extra isn't formatted right

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#36]
http://127.0.0.1:4000/extras/XX-terms.html doesn't look right. Should this be formatted like an episode? Do we want to keep this material in _extras or move the relevant definitions to a glossary (some lessons have this)?

**Comment by raynamharris** [comment]
https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_extras/XX-terms.md

If this episode is being retired, then I think the episode formatting should be removed. 

I think there are three solutions:
- Move the content to a glossary.md file in _extras
- Move the content to a related lesson that is being maintained
- Retire the content all together if it is no longer appropriate
