### ISSUE TITLE
Library Carpentry

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#37]
In about.md the Library Carpentry entry doesn't link to their website or use the new logo. This should be fixed in the lesson template repo.

**Comment by raynamharris** [comment]
The logo appears to be there now (at least I see it here). However, the link is still missing.

**Comment by raynamharris** [comment]
Additionally, there is a large is that SWC and DC are mentioned through, on many many pages, but LC does not appear anywhere. Do we need to create an issue for someone to add LC to everywhere where DC and SWC are mentioned?

**Comment by ErinBecker** [comment]
@raynamharris you know more about this than I do, given your position on the Bridge subcommittee, but from my understanding, Library Carpentry isn't currently included in the merger discussions. I fully believe that they will become an official part of the Carpentries umbrella org in the near future, but since they aren't yet, I don't think they should be added in the text throughout.

**Comment by raynamharris** [comment]
@ErinBecker True, they are not an official Carpentry. I'll modify the pull request to the training-template to only request that a link to the LC website be added.

**Comment by ErinBecker** [comment]
May as well update the logo while we're at it. @weaverbel has some cool LC stickers with a t-square and a clamp. Can we get that as an image?

**Comment by weaverbel** [comment]
The LC logo is in the workshop template repo as Raniere included it in the workshop template redesign. https://github.com/swcarpentry/workshop-template/blob/gh-pages/assets/img/lc-icon-black.png

**Comment by weaverbel** [comment]
Probably good @raynamharris @ErinBecker to see Tracy's comments here: https://github.com/data-lessons/librarycarpentry/issues/48

**Comment by ErinBecker** [comment]
Added to checklist and closing here.
