### ISSUE TITLE
extra exercises

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#39]
There are extra exercise suggestions in http://127.0.0.1:4000/exercises/. These would be more useful if they were incorporated into lessons (potentially marked as alternate exercises).

**Comment by raynamharris** [comment]
Yes! Let's move extra exercises out of instructor notes and into the main lesson. This also helps clean up the guide page as per issue https://github.com/ErinBecker/instructor-training-reorg/issues/41

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
