### ISSUE TITLE
Instructor notes

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#41]
Instructor notes need significant work in order to be most useful to instructors. How much of what is in this file should remain here? Should detailed documentation on running/planning instructor training events go elsewhere (e.g. checklists)? If so, where? What other information would be helpful to have in either the instructor notes or a different piece of documentation?

**Comment by raynamharris** [comment]
I think it could make a lot of sense to split up the document into three pieces:
1. checklists to prepare for the workshop
2. guide for during the workshop which would include all the things that are notes for specific lessons
3. a post-workshop guide that includes the info about the demo sessions and parts of checkout

**Comment by lexnederbragt** [comment]
I second this. Ideally, number 2 would have sections for all episodes with practical information on how to teach the particular material.

**Comment by ErinBecker** [comment]
See notes here: https://github.com/swcarpentry/instructor-training/issues/328 and here: https://github.com/swcarpentry/instructor-training/issues/385. 

Added to checklist and closing here.
