### ISSUE TITLE
Information for Member Organizations

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#42]
There is a file in _extras (http://127.0.0.1:4000/partners/) that has information for members about scheduling and hosting instructor training events. Should this information be hosted here or on the Carpentries website?

**Comment by raynamharris** [comment]
Do you mean this partner policy file? https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_extras/partner_policy.md

I'm open to moving this policy document outside of the training materials. It could be moved to the website and/or to the https://github.com/carpentries/policies repo.

**Comment by ErinBecker** [comment]
Incorporated into checklist and closed here.
