### ISSUE TITLE
Delete instructor training testimonials

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#44]
- [x] The instructor testimonials extra page should be deleted as it it outdated. https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_extras/testimonials.md
- [x] The reference to the testimonials in the 'Why we teach' call out box in the motivation episode (https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_episodes/08-motivation.md) should be deleted. 

Note: This issue closes https://github.com/ErinBecker/instructor-training-reorg/issues/31#issuecomment-314501998

**Comment by lexnederbragt** [comment]
Why remove it? We don't need a testimonial for all trainers - just as the SWC website has testimonials from just a few learners.

Had I caught it earlier I would have voted against removing...

**Comment by raynamharris** [comment]
can we close this @ChristinaLK
