### ISSUE TITLE
Delete coffee break and lunch episodes?

### ISSUE THREAD

**Issue by raynamharris** [ErinBecker/instructor-training-reorg#49]
The Instructor Training Curricula is **the only** Software Carpentry and Data Carpentry curricula that includes episodes for lunches and coffee breaks. I don't know the history of this, so I'm not sure why these materials were setup that way, but I propose an alternative strategy. 

- [x] Delete all the lunch and coffee break episodes
- [x] Create an '_extras/icebreaker.md' file or a section called icebreaks in the instructor notes where we combine a list of potentially useful icebreakers than can be used as the instructor sees fit.

I think this will help streamline the overview schedule that appear on the home page (http://swcarpentry.github.io/instructor-training/) and it will make it easier to navigate between the episodes with more in-depth pedagogical content. 

Does anyone want to vote on that?

**Comment by ErinBecker** [comment]
I was also noticing this yesterday and thought it was odd. I'm in favor of the solution you proposed.

**Comment by ChristinaLK** [comment]
how would y'all feel about also removing the morning "summarize" episodes?  They're basically about filling out minute cards.  @raynamharris @ErinBecker

**Comment by ChristinaLK** [comment]
Ah, is also addressed in #50 .  Will look at that as well.

**Comment by ErinBecker** [comment]
Closed with #90.
