### ISSUE TITLE
You are not your learners

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#5]
Add section on "you are not your learners", what this means and how it affects the way we teach our workshops to 04-expertise.md.

**Comment by ErinBecker** [comment]
Include "expertise reversal effect" in this discussion.

**Comment by raynamharris** [comment]
Currently, there is some prose on this topic in the [instructor notes](https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_extras/guide.md). 

If "you are not your learners" will be covered in detail in 04-expertise.md, then I think that most of the text in the instructor notes should be deleted so as to not be redundant or conflicting.

**Comment by alex-konovalov** [comment]
The test is already in 04-expertise.md, added in commit df5bb4904c385ba393adbf355251d4ad18bed8a8. It remains to delete it from instructor notes to avoid duplication.
