### ISSUE TITLE
Make Learner Profiles exercise more explicit 

### ISSUE THREAD

**Issue by stelfrich** [ErinBecker/instructor-training-reorg#51]
The _Learner Profiles_ exercise in [19-lessons](http://swcarpentry.github.io/instructor-training/19-lessons/#learner-profiles) could be more explicit about "how will **this training** help them?". Maybe "how will the lesson that you are designing help them?".

Another approach would be to first state something like "Find a topic for which you want to design a new lesson (e.g. the one that you have prepared).", to emphasize the idea behind the exercise.

**Comment by ErinBecker** [comment]
Thanks @stelfrich. These are good thoughts. There has been some conversation in the Trainers group about retiring the Learner Profiles exercise. What are peoples thoughts on this?

**Comment by karenword** [comment]
I would prefer to keep it until/unless another activity can fill its role. Whether or not the exercise itself actually generates any "aha" moments, it makes a crucial point (think deeply about your students' perspectives) and walks them through that process in an amusing and memorable way.

**Comment by ErinBecker** [comment]
I was thinking about possibly keeping it but tying it with a look at the recent SWC/DC assessment reports to see who our learners actually are in terms of domains and experience level. I'm not sure those reports give enough information to make a super interesting compare/contrast, but it was certainly surprising to me at least that SWC learners are 50% life scientists.

**Comment by stelfrich** [comment]
> through that process in an amusing and memorable way

I have actually enjoyed that exercise in the most recent instructor training quite a bit. Maybe I was just lost with respect to the context of the whole "process". Now that I think about it, the root for that might be more in the overall structure of the episode than the exercise itself...

**Comment by ErinBecker** [comment]
I have a pending pull request suggesting removing the learning objectives episode and replacing with an episode on developing good exercises and getting feedback on exercise design. Would appreciate your thoughts about this switch. #180

**Comment by ChristinaLK** [comment]
I don't know if there is space, but I like the idea of including learner profiles as an optional exercise in the section on motivation / empathy.  I find this a helpful exercise when training more "technical" people because it sometimes helps people realize that not everyone coming to their workshops wants to learn how to write amazing, optimized code.

**Comment by stelfrich** [comment]
> because it sometimes helps people realize that not everyone coming to their workshops wants to learn how to write amazing, optimized code

That's so true and helpful to realize! 👍

> I have a pending pull request suggesting removing the learning objectives episode and replacing with an episode on developing good exercises and getting feedback on exercise design.

I found the learning objectives really useful and went back to the curricula of my courses to revise and sometimes even formalize the learning objectives. So I don't think that the lesson should be dropped completely, @ErinBecker, but the Reverse Instructional Design section could be superseded by the contents of #180.

**Comment by ErinBecker** [comment]
@stelfrich - @karenword has incorporated learning profiles back into the changes proposed in #180. Could you take a look there and see if it accomplished what you were suggesting? Thanks for your input!

**Comment by ErinBecker** [comment]
Closing based on #180
