### ISSUE TITLE
Number of key points

### ISSUE THREAD

**Issue by IanHawke** [ErinBecker/instructor-training-reorg#53]
With the "7 \pm 2 concepts" from the "Expertise and Memory" episode in mind I was looking at the length of the "Key points" sections at the end of each episode. Some look on the long side. In some cases I think the key points could be more briefly summarized; in others it may indicate too many concepts in one lesson. 

Examples with suggestions:

* Novice and Formative Assessment. 8 points. Re-organize?
  - Make "Goal when teaching novices is to help them construct a usable mental model. To do this, must clear up their misconceptions." a single point rather than two.
  - Make "Assessment is *summative* if done at the end of teaching to see whether learning took place, and *formative* if done during teaching to guide learning." a single point rather than two.
* Expertise and Memory. 9 points. Too many concepts?
  - All the key points look important. Are concept maps sufficiently important and useful to have their own episode?
* Carpentry Teaching Practices. 7 points. Re-organize?
  - Combine first two points?
* Motivation and Demotivation. 9 points. Unsure.
  - Merge final two points?
  - Merge first two points?

**Comment by IanHawke** [comment]
Note that "Never teach alone" is first mentioned and explicitly motivated in "Teaching as a Performance Art", but is only a key summary point in "Carpentry Teaching Practices". If highlighted in the earlier episode then its appearance in the later is a reinforcement and not so overloading?

**Comment by ErinBecker** [comment]
Great points @IanHawke. I'll make sure that as we go through the episodes for the Bug BBQ we're reducing the number of key points for each lesson to ~5 (a relatively safe number for cognitive load) and that they're in the correct episodes.
