### ISSUE TITLE
Odd linebreaks in Lessons and Objectives

### ISSUE THREAD

**Issue by IanHawke** [ErinBecker/instructor-training-reorg#54]
The first paragraph breaks between every sentence, which may be intentional, but in the "Writing lessons" section there's a break in the second sentence between "with" and "misconceptions" which makes me think there may be a more general formatting issue.

**Comment by ErinBecker** [comment]
Thanks Ian! I'll take a look at the formatting during the Bug BBQ to make sure it's all fixed.

**Comment by alex-konovalov** [comment]
Fixed this in #136 - scrolled through all episodes and did not find any other strange line breaks. Also fixed punctuation in several lists at the same time which used a mix of styles before.
