### ISSUE TITLE
Options for teaching in welcome episode

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#56]
Submitted by email. 

The question "Which of these most accurately describes your teaching experience?" [http://swcarpentry.github.io/instructor-training/01-welcome/] does not include options related to non-structured teaching, such as mentoring for STEM outreach programs, running hackathons, conducting scientific demonstrations, or answering questions at museums (or similar).

Perhaps an option could be added along the lines of "I have taught informally through programs such as STEM outreach, hackathons, laboratory demonstrations, and similar activities."

**Comment by DanielleQuinn** [comment]
added - see pull request #100

**Comment by ErinBecker** [comment]
Thanks @DanielleQuinn!
