### ISSUE TITLE
Episode 5 typos and suggestions

### ISSUE THREAD

**Issue by AnnaWilliford** [ErinBecker/instructor-training-reorg#59]
"The first of these presents a nearly-complete use of the same problem-solving strategy just demonstrated with a small number of blanks for the learner to fill in. "  I am confused here - "just demonstrated"? nothing was just demonstrated in this episode

"then ask learners to fill in the blanks in:" - should be "asks"

Key points are carried over from episode 4???

**Comment by kariljordan** [comment]
@AnnaWilliford ask is correct. The sentence would read: 
"For example, someone teaching Python might start by explaining this: then ask learners to fill in the blanks in..."

I removed the words "just demonstrated".

**Comment by ErinBecker** [comment]
Thanks @kariljordan and @AnnaWilliford.

**Comment by ErinBecker** [comment]
Reopened due to key point duplication issue.

**Comment by ErinBecker** [comment]
Key points are now different between episodes 4 and 5.
