### ISSUE TITLE
Episode 12 - comment on links

### ISSUE THREAD

**Issue by DanielleQuinn** [ErinBecker/instructor-training-reorg#81]
Link lessons to text rather than writing them out fully

(they currently looks like this):
Faceting and Clustering in OpenRefine: http://datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine

**Comment by ErinBecker** [comment]
This is a great point @DanielleQuinn. The SWC lessons all set a "lesson homepage" link and then link from that point forward. I'll look into the format for doing this.

**Comment by laderast** [comment]
Addressed in [pull request #115](http://github.com/ErinBecker/instructor-training-reorg/pull/115)
