### ISSUE TITLE
Episode 15 - broken links / comment on link

### ISSUE THREAD

**Issue by DanielleQuinn** [ErinBecker/instructor-training-reorg#83]
Heading: I/We/You v. You/Y'all/We - "discussed earlier"

In the linked page "Screencasting of Tacit Knowledge" (Heading: Up and Down (Solution), the first two links are broken.

Comment: Could the link for "tacit knowledge" be changed to something more relevant? This example is so specific to a particular language / situation that the point we're trying to get across may be lost on learners not familiar with Python.

**Comment by lexnederbragt** [comment]
I couldn't find a better link to tacit knowledge or lateral knowledge transfer. Maybe split that out into a separate issue?
