### ISSUE TITLE
Episodes with no broken links

### ISSUE THREAD

**Issue by DanielleQuinn** [ErinBecker/instructor-training-reorg#84]
Just as a note, I checked links in episodes 1,2, and 8-23.
The following episodes had no broken links:
1, 9 - 10, 12 - 13, 16 - 23

**Comment by ChristinaLK** [comment]
Thanks @DanielleQuinn !  This helps us know where to focus.  :)

**Comment by ErinBecker** [comment]
Links now fixed!
