### ISSUE TITLE
Add section about co-instructors

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#86]
Explicitly talk about what co-instructors and helpers should be doing.

**Comment by ErinBecker** [comment]
Idea is to have a short set of guidelines about how co-instructors who aren't teaching at the moment, and helpers, should interact with the learners and the teaching instructors. 

- Should circulate around the room, even if there are no stickies up. Many learners are so absorbed in their work that they won't think to put up a sticky, but seeing a helper/instructor walk by will remind them to ask for help. 
- Should be taking notes in the Etherpad when not circulating, to help supplement what the instructor is saying and provide a back-up for learners who fall behind.
- Should never take over the learner's keyboard. Even if they have to say "type 'g-e-t-w-d-parenthesis-parenthesis'", it's important for learners to type the commands themselves so that they develop muscle memory.
- Should ask questions themselves when they think the learners as a group may be confused about something the teaching instructor has said. Should ask instructor to slow down as needed.

**Comment by ChristinaLK** [comment]
Where should this go?  Carpentries teaching practices?

**Comment by ErinBecker** [comment]
@ChristinaLK seems like that would be a good fit.

**Comment by ErinBecker** [comment]
Related to discussion here: https://github.com/swcarpentry/instructor-training/issues/176

**Comment by ErinBecker** [comment]
Related to discussion here: https://github.com/swcarpentry/instructor-training/issues/198

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
