### ISSUE TITLE
writing good challenges exercise

### ISSUE THREAD

**Issue by ErinBecker** [ErinBecker/instructor-training-reorg#9]
We have focused in the past on writing MCQs, Parsons problems and faded examples, however, most of the challenges used in our workshops don't follow these models. Replace some of the material with a section on how to write good challenges and a related exercise (05-memory.md).

**Comment by raynamharris** [comment]
Speaking of this... what models do the current challenges use?  

I was looking through this [Creating Publication-Quality Graphics in R](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/) lesson, and I think this might be a great opportunity to where we could incorporate faded examples or parsons problems as challenges.

**Comment by ErinBecker** [comment]
See https://github.com/ErinBecker/instructor-training-reorg/pull/180
