### ISSUE TITLE
Options for previous teaching experience

### ISSUE THREAD

**Issue by cb1610** [ErinBecker/instructor-training-reorg#96]
The question “Which of these most accurately describes your teaching experience?” [http://swcarpentry.github.io/instructor-training/01-welcome/] does not include options related to non-structured teaching, such as mentoring for STEM outreach programs, running hackathons, conducting scientific demonstrations, or answering questions at museums (or similar).

Perhaps an option could be added along the lines of “I have taught informally through programs such as STEM outreach, hackathons, laboratory demonstrations, and similar activities.”

**Comment by ErinBecker** [comment]
Thanks @cb1610, that's a great idea.

**Comment by ErinBecker** [comment]
Addressed with https://github.com/ErinBecker/instructor-training-reorg/pull/100
