### ISSUE TITLE
remove episode numbering on front page?

### ISSUE THREAD

**Issue by ChristinaLK** [ErinBecker/instructor-training-reorg#98]
It's quibble-y, but I don't really like the numbering of the episodes on the front page.  Seems distracting.

**Comment by ErinBecker** [comment]
@ChristinaLK I'm fine with removing the numbering, but I can't see where it's being added from. Do you know where this formatting comes from?

**Comment by ChristinaLK** [comment]
No.  :(  Probably the css somewhere?

**Comment by ChristinaLK** [comment]
I'll look.

**Comment by ChristinaLK** [comment]
I'll try to change it.  This will definitely need a preview to make sure I don't break anything.  :P

**Comment by ChristinaLK** [comment]
See #105

**Comment by ErinBecker** [comment]
Closed with #105.
